<?php
Localization::register([
  'PROFILE' => 'Profil',
  'WELCOME_USERNAME' => 'Välkommen, %s',
  'ATTACHMENTS' => 'Bilagor',
  'MATERIAL' => 'Material',
  'LOGIN' => 'Logga in',
  'REGISTER' => 'Registrera',
  'LOGOUT' => 'Logga ut',
  'INVALID_EMAIL' => 'Ogiltigt email',
  'FIELD_REQUIRED' => 'Detta fält är obligatoriskt',
  'REMEMBER_ME' => 'Kom ihåg mig',
  'FORGOT_PASSWORD' => 'Glömt lösenord',
  'PASSWORD' => 'Lösenord',
  'EMAIL' => 'Email',
  'INTRODUCTION' => 'Introduktion',
  'COURSE' => 'Kurs',
  'JIT_TEST' => 'JTI Test',
  'LEADERSHIP_GRAPH' => 'Ledarskaps Graf',
  'SETTINGS' => 'Inställningar',
  'WRONG_EMAIL_OR_PASSWORD' => 'Fel email eller lösenord',
  'NOTIFICATIONS_METHOD' => 'Önskar påminnelser via:',
  'HOW_OFTEN' => 'Hur ofta',
  'PHONE_NUMBER' => 'Telefon Nummer',
  'UPDATE' => 'Uppdatera',
  'ONE_TIME_A_WEEK' => 'EN GÅNG I VECKAN',
  'ONE_TIME_A_MONTH' => 'EN GÅNG I MÅNADEN',
  'ONE_TIME_A_QUARTER' => 'EN GÅNG PER KVARTAL',
  'ONE_TIME_A_YEAR' => 'EN GÅNG PER ÅR',
]);
