<?php
Localization::register([
  'PROFILE' => 'Profil',
  'WELCOME_USERNAME' => 'Välkommen, %s',
  'ATTACHMENTS' => 'Bilagor',
  'MATERIAL' => 'Material',
  'LOGIN' => 'Logga in',
  'REGISTER' => 'Registrera',
  'LOGOUT' => 'Logga ut',
  'INVALID_EMAIL' => 'Ogiltigt email',
  'FIELD_REQUIRED' => 'Detta fält är obligatoriskt',
  'REMEMBER_ME' => 'Kom ihåg mig',
  'FORGOT_PASSWORD' => 'Glömt lösenord',
  'PASSWORD' => 'Lösenord',
  'EMAIL' => 'Email',
  'INTRODUCTION' => 'Introduktion',
  'COURSE' => 'Kurs',
  'JIT_TEST' => 'JTI Test',
  'LEADERSHIP_GRAPH' => 'Ledarskaps Graf',
  'SETTINGS' => 'Inställningar',
]);
