<?php
Localization::register([
  'PROFILE' => 'Profil',
  'WELCOME_USERNAME' => 'Välkommen, %s',
  'ATTACHMENTS' => 'Bilagor',
  'MATERIAL' => 'Material',
  'LOGIN' => 'Logga in',
  'REGISTER' => 'Registrera',
  'LOGOUT' => 'Logga ut',
  'INVALID_EMAIL' => 'Ogiltigt email',
  'FIELD_REQUIRED' => 'Detta fält är obligatoriskt',
  'REMEMBER_ME' => 'Kom ihåg mig',
  'FORGOT_PASSWORD' => 'Glömt lösenord',
  'PASSWORD' => 'Lösenord',
  'EMAIL' => 'Email',
  'INTRODUCTION' => 'Introduktion',
  'COURSE' => 'Kurs',
  'JIT_TEST' => 'JTI Test',
  'LEADERSHIP_GRAPH' => 'Ledarskapsgraf',
  'SETTINGS' => 'Inställningar',
  'WRONG_EMAIL_OR_PASSWORD' => 'Fel email eller lösenord',
  'NOTIFICATIONS_METHOD' => 'Önskar påminnelser via:',
  'HOW_OFTEN' => 'Hur ofta',
  'PHONE_NUMBER' => 'Telefon Nummer',
  'UPDATE' => 'Uppdatera',
  'SAVE' => 'Spara',
  'INTRO' => 'Guide',

  'ONE_TIME_A_WEEK' => 'En gång per vecka',
  'ONE_TIME_A_MONTH' => 'En gång per månad',
  'ONE_TIME_A_QUARTER' => 'En gång per kvartal',
  'ONE_TIME_A_YEAR' => 'En gång per år',

  'REQUEST_NEW_PASSWORD' => 'Skicka nytt lösenord',
  'PASSWORD_RESET_LINK_SENT' => 'Länk till återställning av ditt lösenord har skickats',
  'BOSS_ROLES' => 'Chefens roller',
  'CONFLICT_MANAGEMENT' => 'Konfliktshantering',
  'LECTURES' => 'Föreläsningar',
  'THIS_IS_NOT_A_VALID_OPTION' => 'Detta är inte en giltig inställning',
  'UPDATED_NOTIFICATION_SUCCESSFULLY' => 'Inställningar sparade!',
  'PASSWORD_CONFIRM' => 'Konfirmera Lösenord',
  'RESET_PASSWORD' => 'Återställ Lösenord',
  'THIS_FIELD_NEED_TO_BE_IDENTICAL_TO_password' => 'Du måste skriva samma lösenord här som i fältet ovan',
]);
